### PR TITLE
Add BuildkiteAgentTokenParameterStorePath

### LINKED ISSUE #8: Add support for BuildkiteAgentTokenParameterStorePath
The main Buildkite elastic ci stack leverages a BuildkiteAgentTokenParameterStorePath parameter which allows for easier infra as code implementation. It enables us to rely on built-in security protocols, instead of having to maintain our own secrets system.

It would be great if we could add support for this parameter in the mac elastic stack as well.

### PR DESCRIPTION
**Pull request by scadu**
Closes #8

### CODE REVIEW

**Review by moskyb — CHANGES_REQUESTED** [review]
Hey @scadu! Thanks for your contribution.

this looks great, and i'd really love to have first-class parameter store support in the elastic stack for mac.

it seems like a couple of things are missing from this PR though; you've added a place to specify the path for the token, but not a place that uses this path for anything.

if you're looking for inspiration on how do do this, the [non-mac elastic stack](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/templates/aws-stack.yml) does a similar thing - i'd be happy to do something like that in this case.

**Comment by scadu** [comment]
@moskyb thanks for the feedback! Indeed, now I see I missed a lot and it won't work automagically. 
I marked PR as a draft now and I'll add the missing pieces in upcoming days.

**Comment by moskyb** [comment]
> it won't work automagically

unfortunately! my job would be a heck of a lot easier....

anyway, lemme know if you run into any problems, happy to help out :)

**Comment by scadu** [comment]
@moskyb, not sure what I was thinking either when I created a PR with this change only. I'm working on adding the required items: IAM role and policy, a script to inject the agent token after agent installation, etc.

**Comment by triarius** [comment]
Apologies @scadu, I just merged another community contributed PR that caused some merge conflicts with yours. It should be a somewhat straight forward fix, though. Let us know if that's not the case though and we can take a look.

**Comment by scadu** [comment]
Closing it for now as I don't plan to work on it now, and it's been a year already.

**Pull request closed without merging**
